server:
  port: 10001
spring:
  application:
    name: platform-passport
  rabbitmq:
    host: 192.168.1.101
    port: 5672
    username: guest
    password: guest
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3307/ft_passport
    username: ft_test
    password: ft_test
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
logging:
  level:
    root: DEBUG
